### ISSUE TITLE
大家觉得 11 月份的回国机票可以买了嘛？

### ISSUE THREAD

**Issue by sarkrui** [USCreditCardGuide/airlines-to-china-covid-19#15]
现在有消息说 航班 10月25号前的比较靠谱，比较确定能飞。但 11 月份后，五个一的限制可能会放宽，大家有没有消息呢？

**Comment by bayshier** [comment]
> 现在有消息说 航班 10月25号前的比较靠谱，比较确定能飞。但 11 月份后，五个一的限制可能会放宽，大家有没有消息呢？

感觉不大可能放宽呢，要么延续，要么更严格
