### ISSUE TITLE
可以把一周多班的航班分开列一下吗？

### ISSUE THREAD

**Issue by Vincent-Cui** [USCreditCardGuide/airlines-to-china-covid-19#8]
比如“UA857 / UA858 | 周三和周六 / 周四和周日” 这种可以分开列成两个row？这样会在抓取的时候会方便很多，你们维护起来其实也更方便一些，就直接往里加就完事了，不需要考虑该航司是不是已经有航班了

**Comment by Vincent-Cui** [comment]
我刚才自己搞了一下,pull request了

**Comment by physixfan** [comment]
#9
